# Generated by Django 5.2.1 on 2026-03-17 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Lugar de almacenamiento',
                'verbose_name_plural': 'Lugares de almacenamiento',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Equipo')),
                ('detailed_spec', models.TextField(blank=True, verbose_name='Especificación técnica detallada')),
                ('total_existing', models.PositiveIntegerField(default=0, verbose_name='Cantidad total existente en la sede')),
                ('quantity_needed', models.PositiveIntegerField(default=0, verbose_name='Cantidad necesaria')),
                ('good_count', models.PositiveIntegerField(default=0, verbose_name='Bueno')),
                ('repairable_count', models.PositiveIntegerField(default=0, verbose_name='Reparable')),
                ('bad_count', models.PositiveIntegerField(default=0, verbose_name='Malo')),
                ('unit_value_uf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor unitario UF (c/iva)')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('careers', models.ManyToManyField(blank=True, to='inventory.career', verbose_name='Carreras')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='inventory.storagelocation', verbose_name='Lugar de almacenamiento')),
                ('subjects', models.ManyToManyField(blank=True, to='inventory.subject', verbose_name='Asignaturas')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('code_type', models.CharField(choices=[('inventory', 'Código inventario'), ('barcode', 'Código barra'), ('serial', 'Serie'), ('other', 'Otro')], default='inventory', max_length=20)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='inventory.equipment')),
            ],
            options={
                'verbose_name': 'Código de equipo',
                'verbose_name_plural': 'Códigos de equipos',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Insumo')),
                ('detailed_spec', models.TextField(blank=True, verbose_name='Especificación técnica detallada')),
                ('total_existing', models.PositiveIntegerField(default=0, verbose_name='Cantidad total existente en el laboratorio / taller')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplies', to='inventory.storagelocation', verbose_name='Lugar de almacenamiento')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['name'],
            },
        ),
    ]
