# Generated by Django 5.2.1 on 2026-03-19 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Área académica')),
            ],
            options={
                'verbose_name': 'Área académica',
                'verbose_name_plural': 'Áreas académicas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Lugar de almacenamiento',
                'verbose_name_plural': 'Lugares de almacenamiento',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_code', models.CharField(max_length=100, unique=True, verbose_name='Código inventario')),
                ('name', models.CharField(max_length=200, verbose_name='Equipo')),
                ('detailed_spec', models.TextField(blank=True, verbose_name='Especificación técnica detallada')),
                ('condition', models.CharField(choices=[('good', 'Bueno'), ('repairable', 'Reparable'), ('bad', 'Malo')], default='good', max_length=20, verbose_name='Estado')),
                ('unit_value_uf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor unitario UF (c/iva)')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('academic_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='inventory.academicarea', verbose_name='Área académica')),
                ('careers', models.ManyToManyField(blank=True, to='inventory.career', verbose_name='Carreras')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='inventory.storagelocation', verbose_name='Lugar de almacenamiento')),
                ('subjects', models.ManyToManyField(blank=True, to='inventory.subject', verbose_name='Asignaturas')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['name', 'inventory_code'],
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Insumo')),
                ('detailed_spec', models.TextField(blank=True, verbose_name='Especificación técnica detallada')),
                ('total_existing', models.PositiveIntegerField(default=0, verbose_name='Cantidad total existente en el laboratorio / taller')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('academic_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplies', to='inventory.academicarea', verbose_name='Área académica')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplies', to='inventory.storagelocation', verbose_name='Lugar de almacenamiento')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad solicitada')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=20)),
                ('academic_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='inventory.academicarea')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='inventory.equipment')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
                ('supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='inventory.supply')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Estudiante'), ('coordinator', 'Coordinador'), ('panol', 'Pañol')], default='student', max_length=20, verbose_name='Rol')),
                ('academic_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='inventory.academicarea', verbose_name='Área académica')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
    ]
