# Generated by Django 5.2.1 on 2026-04-16 01:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_request_sheet_and_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'ordering': ['name'], 'verbose_name': 'Carrera', 'verbose_name_plural': 'Carreras'},
        ),
        migrations.AlterModelOptions(
            name='storagelocation',
            options={'ordering': ['name'], 'verbose_name': 'Lugar de almacenamiento', 'verbose_name_plural': 'Lugares de almacenamiento'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['code', 'name'], 'verbose_name': 'Asignatura', 'verbose_name_plural': 'Asignaturas'},
        ),
        migrations.AlterField(
            model_name='career',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='academic_area',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='inventory.academicarea', verbose_name='Área académica'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='academic_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='inventory.academicarea', verbose_name='Área académica'),
        ),
        migrations.AlterField(
            model_name='request',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='request',
            name='work_groups',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='N° de grupos de trabajo'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_items', to='inventory.equipment', verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad solicitada'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.request', verbose_name='Solicitud'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_items', to='inventory.supply', verbose_name='Insumo'),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Lugar de almacenamiento'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Asignatura'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='academic_area',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='supplies', to='inventory.academicarea', verbose_name='Área académica'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddConstraint(
            model_name='requestitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('equipment__isnull', False), ('supply__isnull', True)), models.Q(('equipment__isnull', True), ('supply__isnull', False)), _connector='OR'), name='requestitem_exactly_one_resource'),
        ),
    ]
